before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos=darwin
        goarch=arm64
        goamd64=v1
    binary: crypt
    main: ./cmd/crypt
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    hooks:
      post:
        - cmd: shasum -a 256 {{ .ArtifactPath }}
          env:
            - SHA256SUM={{ .Env.SHA256SUM }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    ignore:
      - goos=darwin
        goarch=arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: crypt
    homepage: "https://github.com/BuddhiLW/crypt"
    description: "A CLI for steganography; focused on EAS, QRCode and DCT"
    repository:
      name: homebrew-tap
      owner: BuddhiLW
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    goarm: "6"
    test: |
      system "#{bin}/crypt", "help"

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - configs/config.example.yaml

release:
  github:
    owner: BuddhiLW
    name: crypt
  draft: false
  prerelease: false
  name_template: '{{ .ProjectName }} {{ .Version }}'
  release_header: |
    ## What's Changed

    {{ .Changelog }}

    ---
    **Full Changelog**: https://github.com/BuddhiLW/crypt/compare/{{ .PreviousTag }}...{{ .Tag }}

dist: dist

nfpms:
  - maintainer: BuddhiLW <your-email@example.com>
    description: A CLI for steganography; focused on EAS, QRCode and DCT
    homepage: https://github.com/BuddhiLW/crypt
    license: MIT
    formats:
      - deb
      - rpm
    files:
      README.md: /usr/share/doc/crypt/README.md
      LICENSE: /usr/share/doc/crypt/LICENSE
    config_files:
      configs/config.example.yaml: /etc/crypt/config.yaml
    empty_folders:
      - /var/log/crypt
      - /var/lib/crypt
