before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: crypt
    main: ./cmd/crypt
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    hooks:
      post:
        - cmd: shasum -a 256 {{ .ArtifactPath }}
          env:
            - SHA256SUM={{ .Env.SHA256SUM }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# Note: Homebrew and Docker builds are disabled due to CGO dependencies
# For cross-platform distribution, use the Makefile or build natively on each platform

release:
  github:
    owner: BuddhiLW
    name: crypt
  draft: false
  prerelease: false
  name_template: '{{ .ProjectName }} {{ .Version }}'
  release_header: |
    ## What's Changed

    {{ .Changelog }}

    ---
    **Full Changelog**: https://github.com/BuddhiLW/crypt/compare/{{ .PreviousTag }}...{{ .Tag }}

dist: dist

# Note: Package builds (deb/rpm) are disabled due to CGO dependencies
# For package distribution, build natively on each platform
